(defun binary-search (list item)
  (do* ((start 0)
        (end (1- (length list))))
       ((> start end) nil)
    (let* ((mid (floor (/ (+ start end) 2)))
           (guess (elt list mid)))
      (cond ((> guess item)
             (setf end (1- mid)))
            ((< guess item)
             (setf start (1+ mid)))
            (t (return mid))))))
